"""
Static seed data for the mock university API.
Edit these dicts to add more students, rooms, courses, etc.
"""

STUDENTS = {
    "STU-2021-0001": {
        "id": "STU-2021-0001",
        "name": "Ahmad Hafizi bin Roslan",
        "programCode": "BCSJ",
        "faculty": "Computing",
        "year": 3,
        "cgpa": 3.65,
        "enrolStatus": "active",
        "email": "hafizi@graduate.utm.my",
        "phone": "011-11223344",
        "ic": "010101010001",
        "address": "Johor Bahru, Johor",
        "distance_from_campus_km": 80,
    },
    "STU-2022-0042": {
        "id": "STU-2022-0042",
        "name": "Nurul Aina binti Zulkifli",
        "programCode": "BCSJ",
        "faculty": "Computing",
        "year": 2,
        "cgpa": 3.82,
        "enrolStatus": "active",
        "email": "nurul.aina@graduate.utm.my",
        "phone": "011-22334455",
        "ic": "020202020002",
        "address": "Kuala Lumpur",
        "distance_from_campus_km": 340,
    },
    "STU-2023-0118": {
        "id": "STU-2023-0118",
        "name": "Lim Wei Kang",
        "programCode": "BISJ",
        "faculty": "Computing",
        "year": 1,
        "cgpa": 3.10,
        "enrolStatus": "active",
        "email": "weikang@graduate.utm.my",
        "phone": "011-33445566",
        "ic": "030303030003",
        "address": "Skudai, Johor",
        "distance_from_campus_km": 5,
    },
    "STAFF-2018-0007": {
        "id": "STAFF-2018-0007",
        "name": "Dr. Norhana Bt Yahya",
        "programCode": None,
        "faculty": "Computing",
        "year": None,
        "cgpa": None,
        "enrolStatus": "staff",
        "email": "norhana@utm.my",
        "phone": "07-5531234",
        "ic": "780101780001",
        "address": "UTM Skudai Campus",
        "distance_from_campus_km": 0,
    },
}

COURSES = [
    {
        "course_code": "BCS3023",
        "name": "Software Engineering",
        "credit_hours": 3,
        "faculty": "Computing",
        "semester": "2024/2025-2",
        "lecturer": "Dr. Norhana Bt Yahya",
        "max_students": 40,
        "enrolled": 37,
        "available_seats": 3,
        "schedule": "Mon 10:00-12:00, Wed 14:00-15:00",
        "venue": "N28-L2-R1",
    },
    {
        "course_code": "BCS2013",
        "name": "Data Structures & Algorithms",
        "credit_hours": 3,
        "faculty": "Computing",
        "semester": "2024/2025-2",
        "lecturer": "Prof. Dr. Radziah Mohamad",
        "max_students": 45,
        "enrolled": 45,
        "available_seats": 0,
        "schedule": "Tue 08:00-10:00, Thu 10:00-11:00",
        "venue": "N28-L3-R2",
    },
    {
        "course_code": "BIS3033",
        "name": "Database Systems",
        "credit_hours": 3,
        "faculty": "Computing",
        "semester": "2024/2025-2",
        "lecturer": "Dr. Suriayati Chuprat",
        "max_students": 40,
        "enrolled": 32,
        "available_seats": 8,
        "schedule": "Wed 10:00-12:00, Fri 09:00-10:00",
        "venue": "N28-L2-R3",
    },
    {
        "course_code": "MPU3112",
        "name": "Bahasa Melayu Komunikasi 2",
        "credit_hours": 2,
        "faculty": "General Studies",
        "semester": "2024/2025-2",
        "lecturer": "Pn. Azlina Bt Ahmad",
        "max_students": 50,
        "enrolled": 48,
        "available_seats": 2,
        "schedule": "Thu 14:00-16:00",
        "venue": "C14-L1-R5",
    },
    {
        "course_code": "BCS4913",
        "name": "Final Year Project I",
        "credit_hours": 3,
        "faculty": "Computing",
        "semester": "2024/2025-2",
        "lecturer": "Various",
        "max_students": 30,
        "enrolled": 28,
        "available_seats": 2,
        "schedule": "By appointment",
        "venue": "N28 Research Labs",
    },
]

STUDENT_ENROLMENTS = {
    "STU-2021-0001": ["BCS3023", "BCS2013", "MPU3112"],
    "STU-2022-0042": ["BCS3023", "BIS3033", "BCS4913"],
    "STU-2023-0118": ["BIS3033", "MPU3112"],
}

ROOMS = [
    {"roomNo": "KM-A-101", "block": "Kolej Maju", "floor": 1, "type": "single", "status": "available", "monthlyFee": 280, "amenities": ["wifi", "air_conditioner", "study_desk", "wardrobe"], "gender": "male"},
    {"roomNo": "KM-A-102", "block": "Kolej Maju", "floor": 1, "type": "single", "status": "occupied", "monthlyFee": 280, "amenities": ["wifi", "air_conditioner", "study_desk", "wardrobe"], "gender": "male", "occupant_id": "STU-2021-0001"},
    {"roomNo": "KM-A-103", "block": "Kolej Maju", "floor": 1, "type": "double", "status": "available", "monthlyFee": 190, "amenities": ["wifi", "fan", "study_desk", "wardrobe"], "gender": "male"},
    {"roomNo": "KM-A-201", "block": "Kolej Maju", "floor": 2, "type": "single", "status": "available", "monthlyFee": 280, "amenities": ["wifi", "air_conditioner", "study_desk", "wardrobe"], "gender": "male"},
    {"roomNo": "KM-B-101", "block": "Kolej Maju", "floor": 1, "type": "single", "status": "available", "monthlyFee": 280, "amenities": ["wifi", "air_conditioner", "study_desk", "wardrobe"], "gender": "female"},
    {"roomNo": "KM-B-102", "block": "Kolej Maju", "floor": 1, "type": "single", "status": "occupied", "monthlyFee": 280, "amenities": ["wifi", "air_conditioner", "study_desk", "wardrobe"], "gender": "female", "occupant_id": "STU-2022-0042"},
    {"roomNo": "KM-B-103", "block": "Kolej Maju", "floor": 1, "type": "double", "status": "available", "monthlyFee": 190, "amenities": ["wifi", "fan", "study_desk", "wardrobe"], "gender": "female"},
    {"roomNo": "KS-A-101", "block": "Kolej Sejahtera", "floor": 1, "type": "single", "status": "available", "monthlyFee": 310, "amenities": ["wifi", "air_conditioner", "study_desk", "wardrobe", "attached_bathroom"], "gender": "male"},
    {"roomNo": "KS-A-102", "block": "Kolej Sejahtera", "floor": 1, "type": "single", "status": "occupied", "monthlyFee": 310, "amenities": ["wifi", "air_conditioner", "study_desk", "wardrobe", "attached_bathroom"], "gender": "male", "occupant_id": "STU-2023-0118"},
    {"roomNo": "KS-B-101", "block": "Kolej Sejahtera", "floor": 1, "type": "single", "status": "available", "monthlyFee": 310, "amenities": ["wifi", "air_conditioner", "study_desk", "wardrobe", "attached_bathroom"], "gender": "female"},
    {"roomNo": "KS-B-201", "block": "Kolej Sejahtera", "floor": 2, "type": "double", "status": "available", "monthlyFee": 220, "amenities": ["wifi", "air_conditioner", "study_desk"], "gender": "female"},
]

FINANCES = {
    "STU-2021-0001": {
        "outstandingAmount": 1200.00,
        "totalFeesSemester": 4200.00,
        "paidAmount": 3000.00,
        "aidCode": "SCH-002",
        "aidName": "University Merit Scholarship",
        "aidAmount": 3000.00,
        "paymentHistory": [
            {"date": "2025-02-10", "amount": 3000.00, "method": "online_banking", "ref": "TXN-2025-001"},
        ],
        "hasPaymentPlan": False,
    },
    "STU-2022-0042": {
        "outstandingAmount": 0.00,
        "totalFeesSemester": 4200.00,
        "paidAmount": 4200.00,
        "aidCode": "SCH-001",
        "aidName": "Yayasan Biasiswa Negara",
        "aidAmount": 4500.00,
        "paymentHistory": [
            {"date": "2025-02-08", "amount": 4200.00, "method": "scholarship_deduction", "ref": "TXN-2025-002"},
        ],
        "hasPaymentPlan": False,
    },
    "STU-2023-0118": {
        "outstandingAmount": 2800.00,
        "totalFeesSemester": 3600.00,
        "paidAmount": 800.00,
        "aidCode": None,
        "aidName": None,
        "aidAmount": 0.00,
        "paymentHistory": [
            {"date": "2025-02-15", "amount": 800.00, "method": "cash", "ref": "TXN-2025-003"},
        ],
        "hasPaymentPlan": True,
        "paymentPlanDetails": {
            "installments": 4,
            "monthly_amount": 700.00,
            "next_due": "2025-05-01",
        },
    },
}
